from pathlib import Path
import unittest


ROOT = Path(__file__).parents[2]
WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"
RELEASE_WORKFLOW = ROOT / ".github" / "workflows" / "release.yml"
FETCH_SCRIPT = ROOT / "scripts" / "fetch_shared_core.sh"

# Retired pin literals. None of these may appear as literals in workflows,
# scripts, sources, or tests. Build-time provenance files under
# Resources/SharedCore are generated by fetch_shared_core.sh and are exempt.
# Split here so this guard file itself stays literal-free.
FORBIDDEN_LITERALS = (
    "fde" + "2eaf",
    "1629" + "54f2",
    "v0." + "11.0",
    "a8b" + "cd15",
    "f119" + "e7d3",
)

SCANNED_SUFFIXES = (".yml", ".yaml", ".py", ".sh", ".swift")
SCANNED_DIRS = (
    ROOT / ".github" / "workflows",
    ROOT / "scripts",
    ROOT / "Sources",
    ROOT / "Tests",
)
SCANNED_FILES = (ROOT / "project.yml",)


class SharedCoreWorkflowTests(unittest.TestCase):
    def scanned_texts(self) -> list[tuple[str, str]]:
        texts = []
        for directory in SCANNED_DIRS:
            for candidate in sorted(directory.rglob("*")):
                if candidate.is_file() and candidate.suffix in SCANNED_SUFFIXES:
                    texts.append(
                        (str(candidate.relative_to(ROOT)), candidate.read_text(encoding="utf-8"))
                    )
        for candidate in SCANNED_FILES:
            texts.append(
                (str(candidate.relative_to(ROOT)), candidate.read_text(encoding="utf-8"))
            )
        return texts

    def test_no_pinned_core_literals(self) -> None:
        offenders = []
        for name, text in self.scanned_texts():
            for literal in FORBIDDEN_LITERALS:
                if literal in text:
                    offenders.append(f"{name}: {literal}")
        self.assertEqual(offenders, [])

    def test_no_pinned_core_literals_rejects_regressions(self) -> None:
        workflow = WORKFLOW.read_text(encoding="utf-8")
        for literal in FORBIDDEN_LITERALS:
            with self.subTest(literal=literal):
                mutated = workflow + f'\n  CORE_COMMIT: "{literal}"\n'
                offenders = [name for name, text in [("ci.yml", mutated)] for pin in FORBIDDEN_LITERALS if pin in text]
                self.assertIn("ci.yml", offenders)

    def test_workflows_resolve_latest_core_at_build_time(self) -> None:
        for workflow in (WORKFLOW.read_text(encoding="utf-8"), RELEASE_WORKFLOW.read_text(encoding="utf-8")):
            self.assertIn("bash scripts/fetch_shared_core.sh", workflow)
            self.assertNotIn("CORE_COMMIT:", workflow)
            self.assertNotIn("CORE_SHA256:", workflow)
            self.assertNotIn("CORE_RELEASE_TAG:", workflow)
            self.assertNotIn("ref: ${{ env.CORE_COMMIT }}", workflow)
            self.assertNotIn("releases/download/", workflow)
            self.assertNotIn("Check out pinned shared core", workflow)
            self.assertNotIn("Verify pinned source", workflow)

    def test_fetch_script_resolves_verifies_and_records_provenance(self) -> None:
        script = FETCH_SCRIPT.read_text(encoding="utf-8")
        self.assertIn("set -euo pipefail", script)
        self.assertIn("repos/$CORE_REPO/releases/latest", script)
        self.assertIn("gh release download", script)
        self.assertIn("pomodorough_core.wasm", script)
        self.assertIn("gh attestation verify", script)
        self.assertIn("--signer-workflow", script)
        self.assertIn("--source-digest", script)
        self.assertIn("--source-ref", script)
        self.assertIn("CORE_RELEASE_TAG", script)
        self.assertIn("CORE_COMMIT", script)
        self.assertIn("CORE_SHA256", script)
        self.assertIn("CORE_PROVENANCE", script)
        # Fail-closed format gates: tag must be strict SemVer, commit/sha hex.
        self.assertIn("0|[1-9][0-9]*", script)
        self.assertIn("[0-9a-f]{40}", script)
        self.assertIn("[0-9a-f]{64}", script)

    def test_fetch_script_rejects_verification_regressions(self) -> None:
        script = FETCH_SCRIPT.read_text(encoding="utf-8")
        for clause in (
            "gh attestation verify",
            "--source-digest",
            "--source-ref",
            "set -euo pipefail",
            'printf \'%s\' "$TAG" > "$DEST/CORE_RELEASE_TAG"',
            'printf \'%s\' "$COMMIT" > "$DEST/CORE_COMMIT"',
            'printf \'%s\' "$SHA" > "$DEST/CORE_SHA256"',
        ):
            with self.subTest(clause=clause):
                self.assertIn(clause, script)
                self.assertNotIn(clause, script.replace(clause, "", 1))

    def test_built_apps_are_checked_against_resolved_provenance(self) -> None:
        for workflow in (WORKFLOW.read_text(encoding="utf-8"), RELEASE_WORKFLOW.read_text(encoding="utf-8")):
            self.assertIn('expected_sha="$(cat Resources/SharedCore/CORE_SHA256)"', workflow)
            self.assertIn('test "$actual_sha" = "$expected_sha"', workflow)
            self.assertIn("-name 'pomodorough_core.wasm'", workflow)

    def test_release_rejects_shard_skew_and_checks_packaged_apps(self) -> None:
        workflow = RELEASE_WORKFLOW.read_text(encoding="utf-8")
        self.assertIn("Resolve latest shared core release", workflow)
        self.assertIn("shared-core-provenance-ios-simulator", workflow)
        self.assertIn("shared-core-provenance-ios-device", workflow)
        self.assertIn("shared-core-provenance-macos", workflow)
        self.assertIn("core-provenance-ios-simulator/CORE_RELEASE_TAG", workflow)
        self.assertIn("Verify shared core in staged release applications", workflow)
        self.assertIn('test "$verified_apps" -eq 3', workflow)
        self.assertIn("SWIFT_SUPPRESS_WARNINGS=NO", workflow)

    def test_release_packages_ad_hoc_signed_simulator_app_and_smokes_exact_archive(self) -> None:
        workflow = RELEASE_WORKFLOW.read_text(encoding="utf-8")

        def assert_contract(candidate: str) -> None:
            required = (
                'codesign --force --deep --sign - "$ios_simulator_staged_app"',
                'codesign --verify --deep --strict "$ios_simulator_staged_app"',
                'Pomodorough-iOS-Simulator-ad-hoc-signed-non-notarized-${RELEASE_TAG}.zip',
                'ditto -x -k "$archive" "$extracted"',
                'codesign --verify --deep --strict "$app"',
                'launch_output="$(xcrun simctl launch',
                'test -n "$launch_pid"',
                '[[ "$launch_pid" =~ ^[0-9]+$ ]]',
                'ps -p "$launch_pid" >/dev/null 2>&1',
                'is not running after launch',
                'xcrun simctl terminate "$device_id" "$bundle_id"',
            )
            for clause in required:
                self.assertIn(clause, candidate)
            ordered = required[3:]
            self.assertEqual(
                [candidate.index(clause) for clause in ordered],
                sorted(candidate.index(clause) for clause in ordered),
            )
            self.assertNotIn('codesign --remove-signature "$ios_simulator_staged_app"', candidate)
            self.assertNotIn("launchctl print", candidate)
            self.assertNotIn("state = running", candidate)

        assert_contract(workflow)
        survival_clauses = (
            '[[ "$launch_pid" =~ ^[0-9]+$ ]]',
            'ps -p "$launch_pid" >/dev/null 2>&1',
            "is not running after launch",
            'xcrun simctl terminate "$device_id" "$bundle_id"',
        )
        for clause in survival_clauses:
            with self.subTest(clause=clause), self.assertRaises(AssertionError):
                assert_contract(workflow.replace(clause, "", 1))


if __name__ == "__main__":
    unittest.main()
